# Generated by Django 5.2 on 2025-04-16 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terapeuta', '0001_initial'),
        ('decano', '0001_initial'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terapeuta',
            old_name='Abordagem',
            new_name='abordagem',
        ),
        migrations.RemoveField(
            model_name='terapeuta',
            name='Decano',
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='nucleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terapeuta', to='nucleo.nucleo'),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='decano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terapeuta', to='decano.decano'),
        ),
    ]
