# Generated by Django 5.2 on 2025-04-16 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='paciente',
            name='quantidade_de_sessoes',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contapoio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
